/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import App.Utilities;

/**
 *
 * @author Admin
 */
public class GraphViewer extends javax.swing.JPanel {
    
    /**
     * Creates new form NewJPanel
     */
    public GraphViewer() {
        initComponents();
        model = new javax.swing.DefaultListModel();
        usernameList = new javax.swing.JList();
        usernameList.setModel(model);
        userListScroll.setViewportView(usernameList);
        graph = new EDD.Graph();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jSplitPane2 = new javax.swing.JSplitPane();
        addUser = new javax.swing.JButton();
        userListScroll = new javax.swing.JScrollPane();

        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        addUser.setText("+");
        addUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserActionPerformed(evt);
            }
        });
        jSplitPane2.setTopComponent(addUser);
        jSplitPane2.setRightComponent(userListScroll);

        jSplitPane1.setLeftComponent(jSplitPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserActionPerformed
        String validChars = "abcdefghijklmnñopqrstuvwxyzáéíóú0123456789-_.";
        while (true) {
            try {
                
                String username = javax.swing.JOptionPane.showInputDialog("Nombre del usuario nuevo:");
                if (username == null) break;
                
                if (username.equals("")) {
                    throw new java.io.IOException("Debe introducir por lo menos un caracter alfanumérico.");
                } else if (username.contains("..")) {
                    throw new java.io.IOException("No se permiten dos puntos seguidos.");
                } else if (!Utilities.validateCharacters(username, validChars)) {
                    throw new java.io.IOException("Solo se permiten caracteres alfanuméricos, \"_\", \"-\" y \".\".");
                } else if ((username.charAt(username.length() - 1) == ".".charAt(0)) || (username.charAt(0) == ".".charAt(0))) {
                    throw new java.io.IOException("No se permiten puntos al inicio ni al final.");
                }
                    
                int count;
                count = 0;
                for (int i = 0; i < username.length(); i++) {
                    if (username.charAt(i) == "@".charAt(0)) {
                        count++;
                        if (count > 1) {
                            throw new java.io.IOException("No se permite más de un \"@\".");
                        }
                    }
                }
                
                graph.addUser(username);
                model.addElement("@" + username);
                break;
            } catch (java.io.IOException ex) {
                javax.swing.JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
    }//GEN-LAST:event_addUserActionPerformed

    private EDD.Graph graph;
    private javax.swing.DefaultListModel model;
    private javax.swing.JList usernameList;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addUser;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JScrollPane userListScroll;
    // End of variables declaration//GEN-END:variables
}
